name: continuous integration

on:
  push:
    branches:
      - master

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          docker build -t $GITHUB_REPOSITORY:$GITHUB_SHA .
          docker run --rm --mount type=bind,src=$GITHUB_WORKSPACE,dst=/workspaces/tagtical $GITHUB_REPOSITORY:$GITHUB_SHA sh -c 'yarn && yarn test'
