name: continuous integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    container:
      image: customcommander/webdev:3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: yarn
      - name: Test
        run: yarn test
