name: continuous integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          yarn
          yarn test