name: release

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    container:
      image: customcommander/webdev:3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: yarn
      - name: Build
        run: make dist
      - name: Release
        run: yarn semantic-release --no-ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
